workspace:
  base: /test
  path: drupal-site-template

services:
  web:
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.1}
    environment: &env
      - DOCUMENT_ROOT=/test/drupal-site-template
      - DRUPAL_DATABASE_NAME=digit_drupal_site_test_reference
      - DRUPAL_DATABASE_USERNAME=root
      - DRUPAL_DATABASE_PASSWORD=
      - DRUPAL_DATABASE_PREFIX=
      - DRUPAL_DATABASE_HOST=mysql
      - DRUPAL_DATABASE_PORT=3306
      - DRUPAL_ACCOUNT_USERNAME=admin
      - DRUPAL_ACCOUNT_PASSWORD=admin
      - DRUPAL_BASE_URL=http://web:8080/digit-drupal-site-test-reference/web
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug

pipeline:
  # Remove the cache for internal use.
  clean-repo:
    group: init
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.1}
    environment: *env
    volumes:
      - /cache:/cache
    commands:
      - rm -rf /cache/composer/vcs/-test-drupal-site-template
    when:
      matrix:
        PHP_VERSION: 7.1

  # Create project command.
  composer-create-project:
    group: create-project
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.1}
    environment: *env
    volumes:
      - /cache:/cache
    commands:
      - composer create-project --repository-url=packages.json --ansi --no-progress --no-interaction openeuropa/drupal-site-template digit-drupal-site-test-reference

  # Initialize git.
  git-init:
    group: git-init
    image: fpfis/httpd-php-ci:7.1
    environment: *env
    commands:
      - cd digit-drupal-site-test-reference
      - git init

  # Install the drupal site.
  site-install:
    group: installation-site
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.1}
    environment: *env
    commands:
      - cd digit-drupal-site-test-reference
      - ./vendor/bin/run toolkit:install-clean

  # Export of the configuration.
  export-config:
    group: export-config
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.1}
    environment: *env
    commands:
      - cd digit-drupal-site-test-reference
      - ./vendor/bin/drush cex -y

  # Run grumphp tests.
  test-grumphp:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.1}
    environment: *env
    commands:
      - cd digit-drupal-site-test-reference
      - ./vendor/bin/grumphp run

  # Run behat tests.
  test-behat:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION=7.1}
    environment: *env
    commands:
      - cd digit-drupal-site-test-reference
      - ./vendor/bin/behat --strict

matrix:
  PHP_VERSION:
    - 7.1
    - 7.2
