name: CI

on:
  push:
    branches: [ agencies ]
  pull_request:
    branches: [ agencies ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create a project
        run: |
          composer create-project --repository-url=packages.json --ansi --no-progress --no-interaction vever001/drupal-site-template digit-drupal-site-test-reference
          cd digit-drupal-site-test-reference
          git init

      - name: Start Docker compose
        run: |
          cd digit-drupal-site-test-reference
          id
          cp ../.github/workflows/docker-compose.override.yml ./
          docker-compose up -d
          sleep 10

      - name: Install site
        run: |
          cd digit-drupal-site-test-reference
          docker-compose exec -T --user fpfis web ./vendor/bin/run toolkit:install-clean

      - name: Test project:config-status command
        run: |
          cd digit-drupal-site-test-reference
          docker-compose exec -T --user fpfis web ./vendor/bin/drush cex -y
          docker-compose exec -T --user fpfis web ./vendor/bin/drush project:config-status

      - name: Test PHPCS, Behat and PHPUnit
        run: |
          cd digit-drupal-site-test-reference
          docker-compose exec -T --user fpfis web ./vendor/bin/run toolkit:test-phpcs
          docker-compose exec -T --user fpfis web ./vendor/bin/run toolkit:test-behat
          docker-compose exec -T --user fpfis web ./vendor/bin/phpunit
